package io.github.miklires.mbans.database;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import io.github.miklires.mbans.MBans;
import io.github.miklires.mbans.config.ConfigManager;

import java.io.File;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.Locale;

public class DatabaseManager {

    private final MBans plugin;
    private HikariDataSource dataSource;
    private StorageType type;

    public DatabaseManager(MBans plugin) {
        this.plugin = plugin;
    }

    public void initialize() throws SQLException {
        ConfigManager cfg = plugin.getConfigManager();
        type = cfg.getStorageType();

        HikariConfig hk = new HikariConfig();
        hk.setJdbcUrl(jdbcUrl(cfg));
        hk.setDriverClassName(driverClass(type));
        if (type != StorageType.H2 && type != StorageType.SQLITE) {
            hk.setUsername(cfg.getDbUser());
            hk.setPassword(cfg.getDbPassword());
        }
        hk.setMaximumPoolSize(type == StorageType.SQLITE ? 1 : cfg.getDbPoolSize());
        hk.setMinimumIdle(1);
        hk.setConnectionTimeout(cfg.getConnectionTimeoutMillis());
        hk.setMaxLifetime(cfg.getMaxLifetimeMillis());
        hk.setPoolName("mBans-" + type.name());
        if (type == StorageType.SQLITE) hk.setConnectionInitSql("PRAGMA foreign_keys=ON");

        dataSource = new HikariDataSource(hk);
        migrate();
    }

    private String jdbcUrl(ConfigManager cfg) {
        if (!cfg.getJdbcUrl().isBlank()) return cfg.getJdbcUrl();

        File dataFolder = plugin.getDataFolder();
        if (!dataFolder.exists() && !dataFolder.mkdirs()) {
            plugin.getLogger().warning("Could not create plugin data directory");
        }
        String path = new File(dataFolder, cfg.getStorageFile()).getAbsolutePath().replace('\\', '/');
        return switch (type) {
            case H2 -> "jdbc:h2:file:" + path + ";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";
            case SQLITE -> "jdbc:sqlite:" + path + ".db";
            case MYSQL -> "jdbc:mysql://" + cfg.getDbHost() + ":" + cfg.getDbPort() + "/" + cfg.getDbName()
                    + "?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true";
            case MARIADB -> "jdbc:mariadb://" + cfg.getDbHost() + ":" + cfg.getDbPort() + "/" + cfg.getDbName();
            case POSTGRESQL -> "jdbc:postgresql://" + cfg.getDbHost() + ":" + cfg.getDbPort() + "/" + cfg.getDbName();
        };
    }

    private String driverClass(StorageType storageType) {
        return switch (storageType) {
            case H2 -> "org.h2.Driver";
            case SQLITE -> "org.sqlite.JDBC";
            case MYSQL -> "com.mysql.cj.jdbc.Driver";
            case MARIADB -> "org.mariadb.jdbc.Driver";
            case POSTGRESQL -> "org.postgresql.Driver";
        };
    }

    private void migrate() throws SQLException {
        try (Connection c = getConnection(); Statement st = c.createStatement()) {
            st.executeUpdate("CREATE TABLE IF NOT EXISTS mbans_schema_version (version INTEGER PRIMARY KEY, installed_at BIGINT NOT NULL)");
        }

        int version = schemaVersion();
        if (version < 1) {
            migration1();
            setSchemaVersion(1);
        }
        if (version < 2) {
            migration2();
            setSchemaVersion(2);
        }
    }

    private int schemaVersion() throws SQLException {
        try (Connection c = getConnection(); Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT MAX(version) FROM mbans_schema_version")) {
            return rs.next() ? rs.getInt(1) : 0;
        }
    }

    private void setSchemaVersion(int version) throws SQLException {
        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(
                "INSERT INTO mbans_schema_version (version, installed_at) VALUES (?, ?)")) {
            ps.setInt(1, version);
            ps.setLong(2, Instant.now().getEpochSecond());
            ps.executeUpdate();
        }
    }

    private void migration1() throws SQLException {
        String identity = switch (type) {
            case H2 -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case SQLITE -> "INTEGER PRIMARY KEY AUTOINCREMENT";
            case MYSQL, MARIADB -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> "BIGSERIAL PRIMARY KEY";
        };
        String sql = """
                CREATE TABLE IF NOT EXISTS mbans_punishments (
                    id %s,
                    type VARCHAR(16) NOT NULL,
                    target_uuid VARCHAR(36),
                    target_name VARCHAR(64),
                    target_ip VARCHAR(45),
                    reason TEXT,
                    issued_by_uuid VARCHAR(36),
                    issued_by_name VARCHAR(64) NOT NULL,
                    issued_at BIGINT NOT NULL,
                    expires_at BIGINT,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    revoked_by_name VARCHAR(64),
                    revoked_at BIGINT,
                    revoke_reason VARCHAR(255)
                )
                """.formatted(identity);
        try (Connection c = getConnection(); Statement st = c.createStatement()) {
            st.executeUpdate(sql);
        }
        createIndex("mbans_punishments", "idx_mbans_target_type_active", "target_uuid, type, active");
        createIndex("mbans_punishments", "idx_mbans_ip_active", "target_ip, active");
        createIndex("mbans_punishments", "idx_mbans_target_name", "target_name");
        createIndex("mbans_punishments", "idx_mbans_issuer", "issued_by_name");
    }

    private void migration2() throws SQLException {
        addColumn("mbans_punishments", "evidence", "TEXT");
        addColumn("mbans_punishments", "appeal_id", "VARCHAR(16)");
        addColumn("mbans_punishments", "silent", "BOOLEAN NOT NULL DEFAULT FALSE");
        addColumn("mbans_punishments", "server_name", "VARCHAR(64)");

        String identity = switch (type) {
            case H2 -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case SQLITE -> "INTEGER PRIMARY KEY AUTOINCREMENT";
            case MYSQL, MARIADB -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> "BIGSERIAL PRIMARY KEY";
        };
        try (Connection c = getConnection(); Statement st = c.createStatement()) {
            st.executeUpdate(("""
                    CREATE TABLE IF NOT EXISTS mbans_player_history (
                        id %s,
                        player_uuid VARCHAR(36) NOT NULL,
                        player_name VARCHAR(64) NOT NULL,
                        player_ip VARCHAR(45),
                        seen_at BIGINT NOT NULL
                    )
                    """).formatted(identity));
            st.executeUpdate(("""
                    CREATE TABLE IF NOT EXISTS mbans_punishment_log (
                        id %s,
                        punishment_id BIGINT NOT NULL,
                        action VARCHAR(16) NOT NULL,
                        server_name VARCHAR(64) NOT NULL,
                        created_at BIGINT NOT NULL
                    )
                    """).formatted(identity));
            st.executeUpdate(("""
                    CREATE TABLE IF NOT EXISTS mbans_ip_allowlist (
                        id %s,
                        punishment_id BIGINT NOT NULL,
                        player_uuid VARCHAR(36) NOT NULL
                    )
                    """).formatted(identity));
            st.executeUpdate(("""
                    CREATE TABLE IF NOT EXISTS mbans_staff_notes (
                        id %s,
                        player_uuid VARCHAR(36) NOT NULL,
                        author_uuid VARCHAR(36),
                        author_name VARCHAR(64) NOT NULL,
                        note TEXT NOT NULL,
                        created_at BIGINT NOT NULL
                    )
                    """).formatted(identity));
        }
        createIndex("mbans_player_history", "idx_mbans_history_uuid", "player_uuid, seen_at");
        createIndex("mbans_player_history", "idx_mbans_history_ip", "player_ip, seen_at");
        createIndex("mbans_punishment_log", "idx_mbans_log_id", "id");
        createIndex("mbans_ip_allowlist", "idx_mbans_allow", "punishment_id, player_uuid");
        createIndex("mbans_staff_notes", "idx_mbans_notes_uuid", "player_uuid, created_at");
    }

    private void addColumn(String table, String column, String definition) throws SQLException {
        if (hasColumn(table, column)) return;
        try (Connection c = getConnection(); Statement st = c.createStatement()) {
            st.executeUpdate("ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition);
        }
    }

    private boolean hasColumn(String table, String column) throws SQLException {
        try (Connection c = getConnection()) {
            DatabaseMetaData meta = c.getMetaData();
            for (String name : new String[]{table, table.toUpperCase(Locale.ROOT), table.toLowerCase(Locale.ROOT)}) {
                try (ResultSet rs = meta.getColumns(null, null, name, column)) {
                    if (rs.next()) return true;
                }
                try (ResultSet rs = meta.getColumns(null, null, name, column.toUpperCase(Locale.ROOT))) {
                    if (rs.next()) return true;
                }
            }
            return false;
        }
    }

    private void createIndex(String table, String index, String columns) throws SQLException {
        if (hasIndex(table, index)) return;
        try (Connection c = getConnection(); Statement st = c.createStatement()) {
            st.executeUpdate("CREATE INDEX " + index + " ON " + table + " (" + columns + ")");
        }
    }

    private boolean hasIndex(String table, String index) throws SQLException {
        try (Connection c = getConnection()) {
            DatabaseMetaData meta = c.getMetaData();
            for (String name : new String[]{table, table.toUpperCase(Locale.ROOT), table.toLowerCase(Locale.ROOT)}) {
                try (ResultSet rs = meta.getIndexInfo(null, null, name, false, false)) {
                    while (rs.next()) {
                        String current = rs.getString("INDEX_NAME");
                        if (current != null && current.equalsIgnoreCase(index)) return true;
                    }
                }
            }
            return false;
        }
    }

    public Connection getConnection() throws SQLException {
        if (dataSource == null) throw new SQLException("Storage is not initialized");
        return dataSource.getConnection();
    }

    public StorageType getType() {
        return type;
    }

    public void shutdown() {
        if (dataSource != null && !dataSource.isClosed()) dataSource.close();
    }
}
